[server]
port = 5564

[node]
detect-drivers = false

[relay]
url = "http://localhost:4773"
status-endpoint = "/status"
configs = [
    "1", "{\"platformName\": \"android\", \"appium:automationName\": \"UIAutomator2\", \"appium:udid\": \"RZCWB10MTCM\", \"appium:platformVersion\": \"15\", \"appium:systemPort\": \"8105\"}"
]