[server]
port = 5559

[node]
detect-drivers = false

[relay]
url = "http://localhost:4723"
status-endpoint = "/status"
configs = [
    "1", "{\"platformName\": \"android\", \"appium:udid\": \"emulator-5554\", \"appium:automationName\": \"UIAutomator2\", \"appium:systemPort\": \"8100\"}"
]