[server]
port = 5561

[node]
detect-drivers = false

[relay]
url = "http://localhost:4753"
status-endpoint = "/status"
configs = [
    "1", "{\"platformName\": \"iOS\", \"appium:udid\": \"00008110-001C58E03689A01E\", \"appium:automationName\": \"XCUITest\", \"appium:usePrebuiltWDA\": true, \"appium:webDriverAgentUrl\": \"http://localhost:8104\",  \"appium:updatedWDABundleId\": \"rs.yettelbank.WebDriverAgentRunner4\"}"
]
